Update base image used for prow tests to use Go 1.18
Fix issues in e2e tests resulting from newer packages for unix libraries
being incompatible with Go <1.17. CI before this commit fail with

    > # golang.org/x/sys/unix
    > vendor/golang.org/x/sys/unix/syscall.go:83:16: undefined: unsafe.Slice
    > vendor/golang.org/x/sys/unix/syscall_linux.go:2256:9: undefined: unsafe.Slice
    > vendor/golang.org/x/sys/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
    > vendor/golang.org/x/sys/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice

unsafe.Slice was added in Go 1.17.

This updates the base image used for Prow CI jobs to Go 1.18, matching
the rest of the repo.

Signed-off-by: Angel Misevski <amisevsk@redhat.com>